Display: Avoid another ArrayIndexOutOfBoundsException and catch if necessary
Log provided by andreasltcf of xda

FATAL EXCEPTION: main
Process: com.android.settings, PID: 7139
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
at android.app.ActivityThread.performLaunchActivity(A ctivityThread.java:2298)
at android.app.ActivityThread.handleLaunchActivity(Ac tivityThread.java:2360)
at android.app.ActivityThread.access$800(ActivityThre ad.java:144)
at android.app.ActivityThread$H.handleMessage(Activit yThread.java:1278)
at android.os.Handler.dispatchMessage(Handler.java:10 2)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.jav a:5223)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCa ller.run(ZygoteInit.java:898)
at com.android.internal.os.ZygoteInit.main(ZygoteInit .java:693)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
at com.android.settings.DisplaySettings.updateTimeout PreferenceDescription(DisplaySettings.java:344)
at com.android.settings.DisplaySettings.onCreate(Disp laySettings.java:167)
at android.app.Fragment.performCreate(Fragment.java:2 031)
at android.app.FragmentManagerImpl.moveToState(Fragme ntManager.java:863)
at android.app.FragmentManagerImpl.moveToState(Fragme ntManager.java:1067)
at android.app.BackStackRecord.run(BackStackRecord.ja va:833)
at android.app.FragmentManagerImpl.execPendingActions (FragmentManager.java:1452)
at android.app.FragmentManagerImpl.executePendingTran sactions(FragmentManager.java:483)
at com.android.settings.SettingsActivity.switchToFrag ment(SettingsActivity.java:955)
at com.android.settings.SettingsActivity.onCreate(Set tingsActivity.java:581)
at android.app.Activity.performCreate(Activity.java:5 933)
at android.app.Instrumentation.callActivityOnCreate(I nstrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(A ctivityThread.java:2251)
... 10 more